### ISSUE TITLE
Issue : password in the database are not hashed

### ISSUE THREAD

**Issue by afaf98** [NataliaPeneva/donatello#3]
Hi Natalia, 
I'm using your backend and I discovered some issues in it : 
### All the password in the database are in plain text
- This means that if someone gets access to the database, they can log in to every account.
- You can easily resolve this issue by hashing the password, you can use this [library](https://www.npmjs.com/package/bcrypt) 
- Before you save a user you can convert the password in hash, You can use sequelize hook for that here is an [example](https://github.com/afaf98/Backend_IGClone/blob/9ee5457ae29e40221a573e4be605c219a1f3bb3f/models/user.js#L41)
- When you want to check a password you can user bcrypt compare metho, here is an [example](https://github.com/afaf98/Backend_IGClone/blob/9ee5457ae29e40221a573e4be605c219a1f3bb3f/models/user.js#L9)

![Screenshot from 2021-05-14 17-10-26](https://user-images.githubusercontent.com/44358838/118292015-7e4f6480-b4d8-11eb-9470-8adf914c1f96.png)

### When using the /users route to sign up the response return all the data of the user, even the password, 
- The best thing to do is to return a message as "Logged in" " Welcome" or anything you prefer to send back as a response.
- You could also send back a token, if the sign up is successful.

![Screenshot from 2021-05-14 17-07-24](https://user-images.githubusercontent.com/44358838/118292021-7ee7fb00-b4d8-11eb-965f-a89cf1a92a71.png)

**Comment by NataliaPeneva** [comment]
Hi Afaf,

Password hashing is live.

/users route now returns: "Account successfully created". No token returned since the users still would need to login with username and password at the /login endpoint.
