### ISSUE TITLE
Issue : Error messages are not normalized 

### ISSUE THREAD

**Issue by afaf98** [NataliaPeneva/donatello#4]
Hello Natalia, 
I'm working on the Frontend for the Donatello App, and I discovered that the error format is not consistent. 
That means that some errors are inside an object and others they are just plain text.

For example, in line 71 you sent back a successful response as an object
and in line 74 you used plain text.

![Screenshot from 2021-05-17 15-48-01](https://user-images.githubusercontent.com/44358838/118500334-fe1f3e00-b727-11eb-8271-623726705208.png)

It would be nice to discuss the best format for error handling and response messages to use tomorrow, and if it's best to write personalized error messages.

Hope to hear from you soon :)

**Comment by NataliaPeneva** [comment]
Error messages standardized in the format below:
{ message: error.message, error }
